%importdata
clc,clear
close all
D1=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\21L.mat')
D2=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\25L.mat')
D3=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\30L.mat')
D4=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\34L.mat')
D5=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\40L.mat')
D6=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\42L.mat')
D7=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\52L.mat')
D8=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\56L.mat')
D9=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\65L.mat')
D10=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\72L.mat')
D11=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\74L.mat')
D12=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\76L.mat')
D13=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\78L.mat')
D14=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\83L.mat')
D15=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\87L.mat')
D16=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\92L.mat')
D17=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\94L.mat')
D18=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\96L.mat')
D19=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\98L.mat')
D20=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\500L.mat')
D21=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\600L.mat')
D22=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\700L.mat')
D23=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\900L.mat')
D24=load('E:\NCKU_experimental\SurfaceRoughness_0627\result Video\dataBase\1000L.mat')
